import type { Activity, FollowUp, Lead, Note, Settings, Template } from '../types'
const key='nextStudioSalesData';
const defaults:Settings={name:'Richard',company:'Next Studio',phone:'',email:'',website:'https://www.nextstudio.agency',digitalCardUrl:'https://www.nextstudio.agency/card/richard',bookingUrl:'https://calendar.app.google/rVAAWr9ECSrbN6yx9',currency:'USD',landingUrls:{}};
const templates:Template[]=[
 {id:'initial',category:'initial',name:'Initial Contact',en:"Hi {firstName}, I came across {businessName} and wanted to reach out because I have an idea that may help your business improve its digital presence and attract more customers. I'm Richard from Next Studio. May I send you some information?",es:'Hola {firstName}, estuve viendo {businessName} y quería contactarte porque tengo una idea que podría ayudarte a mejorar la presencia digital de tu negocio y atraer más clientes. Soy Richard de Next Studio. ¿Te puedo enviar información?'},
 {id:'voice',category:'voice',name:'Voice Note',en:'Hi {firstName}, this is Richard from Next Studio. I took a look at {businessName} and believe there may be an opportunity to improve how your business presents itself online and connects with customers.',es:'Hola {firstName}, soy Richard de Next Studio. Estuve viendo {businessName} y creo que existe una oportunidad para mejorar cómo tu negocio se presenta en internet y conecta con sus clientes.'},
 {id:'landing',category:'landing',name:'Landing Page',en:"Here's a quick page where you can see how this solution works: {landingUrl}",es:'Aquí puedes ver rápidamente cómo funciona esta solución: {landingUrl}'},
 {id:'card',category:'card',name:'Digital Card',en:"And here's my digital card with my contact information, projects and appointment booking: {digitalCardUrl}",es:'Y aquí tienes mi tarjeta digital con mis datos de contacto, proyectos y opción para agendar una cita: {digitalCardUrl}'},
 {id:'followup',category:'followup',name:'Follow-up',en:'Hi {firstName}, just following up on the information I sent you about {service}. Did you get a chance to take a look?',es:'Hola {firstName}, quería dar seguimiento a la información que te envié sobre {service}. ¿Tuviste oportunidad de revisarla?'},
 {id:'appointment',category:'appointment',name:'Appointment',en:"If you'd like, we can have a quick virtual consultation. Choose a convenient time here: {bookingUrl}",es:'Si deseas, podemos tener una consulta virtual rápida. Puedes elegir un horario conveniente aquí: {bookingUrl}'},
];
type DB={leads:Lead[];notes:Note[];activities:Activity[];followUps:FollowUp[];settings:Settings;templates:Template[]};
const empty=():DB=>({leads:[],notes:[],activities:[],followUps:[],settings:defaults,templates});
export const storage={get:():DB=>{try{return {...empty(),...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return empty()}},save:(db:DB)=>localStorage.setItem(key,JSON.stringify(db)),reset:()=>localStorage.removeItem(key),defaults:()=>({settings:defaults,templates}),export:()=>JSON.stringify(storage.get(),null,2),import:(raw:string)=>{const d=JSON.parse(raw);if(!Array.isArray(d.leads)||!d.settings)throw new Error('Invalid backup');storage.save({...empty(),...d})},language:()=>localStorage.getItem('nextStudioSalesLanguage')==='es'?'es':'en',setLanguage:(v:string)=>localStorage.setItem('nextStudioSalesLanguage',v)};
