import { useState } from "react";
import { Brain, CircleAlert, RefreshCw, ShieldCheck, Sparkles } from "lucide-react";
import { requestOpenAI } from "./services/ai/openAISalesAI";
import { intelligence } from "./Phase2";
import type { Language, Lead } from "./types";
import { statusLabel } from "./i18n";

const tx = (lang: Language, en: string, es: string) => lang === "es" ? es : en;
const today = () => new Date().toISOString().slice(0, 10);
type Cache = { brief?: { text: string; provider: string; generatedAt: string }; analyses?: Record<string, any>; openAI?: boolean };
const read = (): Cache => { try { return JSON.parse(localStorage.getItem("nextStudioSalesAI") || "{}"); } catch { return {}; } };
const write = (value: Cache) => localStorage.setItem("nextStudioSalesAI", JSON.stringify(value));
const localAnalysis = (lead: Lead, db: any, lang: Language) => { const info = intelligence(lead, db), overdue = lead.nextFollowUp && lead.nextFollowUp < today(); return { summary: tx(lang, `${lead.firstName} is a ${statusLabel(lang, "priority", info.priority)} priority opportunity for ${lead.service}.`, `${lead.firstName} es una oportunidad de prioridad ${statusLabel(lang, "priority", info.priority)} para ${lead.service}.`), signals: [...(lead.potentialValue >= 1000 ? [tx(lang, "High deal value", "Alto valor estimado")] : []), ...(lead.stage === "appointment" ? [tx(lang, "Scheduled meeting", "Cita programada")] : [])], risks: [...(overdue ? [tx(lang, "Follow-up overdue", "Seguimiento vencido")] : []), ...(!lead.email ? [tx(lang, "Missing contact information", "Información de contacto incompleta")] : [])], focus: tx(lang, "Use a focused follow-up and ask for the next decision step.", "Usa un seguimiento enfocado y solicita el próximo paso de decisión."), provider: "local", generatedAt: new Date().toISOString(), probability: Math.min(95, Math.round(info.score * .78 + (lead.stage === "appointment" ? 10 : 0))) }; };

export function AIHub({ db, lang, notify }: { db: any; lang: Language; notify: (value: string) => void }) {
  const [cache, setCache] = useState<Cache>(read()), [busy, setBusy] = useState(false);
  const active = db.leads.filter((lead: Lead) => !["won", "lost"].includes(lead.stage));
  const priorities = [...active].sort((a, b) => intelligence(b, db).score - intelligence(a, db).score).slice(0, 5);
  const brief = cache.brief?.text || tx(lang, `You have ${priorities.length} active prospects to prioritize today. Focus on the highest-value conversations and any overdue follow-ups.`, `Tienes ${priorities.length} prospectos activos para priorizar hoy. Enfócate en las conversaciones de mayor valor y los seguimientos vencidos.`);
  const update = (value: Cache) => { setCache(value); write(value); };
  const refresh = async () => { setBusy(true); const response: any = cache.openAI ? await requestOpenAI<any>("sales_brief", { activeProspects: active.length, priorities: priorities.map((lead: Lead) => ({ name: lead.firstName, value: lead.potentialValue, stage: lead.stage })) }) : { provider: "local" }; update({ ...cache, brief: { text: response.result?.brief || brief, provider: response.provider, generatedAt: new Date().toISOString() } }); setBusy(false); notify(response.fallback ? tx(lang, "Fallback active", "Fallback activo") : tx(lang, "Brief updated", "Resumen actualizado")); };
  return <><div className="page-title"><div><h1>{tx(lang, "AI Sales Center", "Centro de Ventas IA")}</h1><p>{tx(lang, "Secure assistance with a local fallback", "Asistencia segura con alternativa local")}</p></div></div><div className="ai-layout"><section className="panel ai-card"><div className="ai-head"><Brain /><h2>{tx(lang, "AI Settings", "Configuración de IA")}</h2></div><p>{cache.openAI ? tx(lang, "OpenAI is enabled. Local intelligence is used if the server is unavailable.", "OpenAI está activado. Se usa inteligencia local si el servidor no está disponible.") : tx(lang, "Local AI Engine is active.", "El motor local de IA está activo.")}</p><div className="toggle"><span>{tx(lang, "Use OpenAI", "Usar OpenAI")}</span><input type="checkbox" checked={!!cache.openAI} onChange={(event) => { update({ ...cache, openAI: event.target.checked }); notify(tx(lang, "AI provider preference saved", "Preferencia de proveedor guardada")); }} /></div><small>{tx(lang, "Model: gpt-5-mini · API key never appears in the browser.", "Modelo: gpt-5-mini · La clave nunca aparece en el navegador.")}</small><button onClick={async () => { setBusy(true); const response = await requestOpenAI("connection_test", { ping: "safe test" }); setBusy(false); notify(response.provider === "openai" ? tx(lang, "Connection successful", "Conexión exitosa") : tx(lang, "API key not configured — Local AI active", "Clave API no configurada — IA local activa")); }} disabled={busy}><ShieldCheck size={15} />{tx(lang, "Test AI Connection", "Probar conexión IA")}</button></section><section className="panel ai-card"><div className="ai-head"><Sparkles /><h2>{tx(lang, "AI Sales Brief", "Resumen de ventas IA")}</h2></div><p>{brief}</p><small>{cache.brief?.provider === "openai" ? "OpenAI" : tx(lang, "Using Local AI Engine", "Usando IA local")}</small><button className="primary" disabled={busy} onClick={refresh}><RefreshCw size={15} />{busy ? tx(lang, "Generating...", "Generando...") : tx(lang, "Refresh Brief", "Actualizar resumen")}</button></section></div><section className="panel"><h2>{tx(lang, "Today's Priorities", "Prioridades de hoy")}</h2><div className="priority-list">{priorities.map((lead: Lead) => { const info = intelligence(lead, db); return <article key={lead.id}><div><b>{lead.firstName} {lead.lastName}</b><span>{tx(lang, "AI Score", "Puntaje IA")} {info.score} · {lead.potentialValue.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 })}</span></div><em>{statusLabel(lang, "priority", info.priority)}</em><small>{info.reason}</small></article>; })}</div></section></>;
}

export function ProspectAnalysis({ lead, db, lang, notify }: { lead: Lead; db: any; lang: Language; notify: (value: string) => void }) {
  const [cache, setCache] = useState<Cache>(read()), [busy, setBusy] = useState(false);
  const analysis = cache.analyses?.[lead.id] || localAnalysis(lead, db, lang);
  const refresh = async () => { setBusy(true); const response: any = cache.openAI ? await requestOpenAI<any>("prospect_analysis", { firstName: lead.firstName, businessName: lead.business, service: lead.service, stage: lead.stage, estimatedValue: lead.potentialValue }) : { provider: "local" }; const next = { ...localAnalysis(lead, db, lang), ...response.result, provider: response.provider, generatedAt: new Date().toISOString() }; const value = { ...cache, analyses: { ...cache.analyses, [lead.id]: next } }; write(value); setCache(value); setBusy(false); notify(response.fallback ? tx(lang, "Fallback active", "Fallback activo") : tx(lang, "Analysis updated", "Análisis actualizado")); };
  return <section className="panel ai-card"><div className="ai-head"><Brain /><h2>{tx(lang, "AI Prospect Analysis", "Análisis IA del prospecto")}</h2></div><h3>{tx(lang, "Opportunity Summary", "Resumen de oportunidad")}</h3><p>{analysis.summary}</p><h3>{tx(lang, "Buying Signals", "Señales de compra")}</h3><div className="chips">{analysis.signals.length ? analysis.signals.map((value: string) => <span key={value}>{value}</span>) : <span>{tx(lang, "No confirmed signals yet", "Aún no hay señales confirmadas")}</span>}</div><h3>{tx(lang, "Sales Risk", "Riesgos de venta")}</h3><div className="chips risk">{analysis.risks.length ? analysis.risks.map((value: string) => <span key={value}><CircleAlert size={13} />{value}</span>) : <span>{tx(lang, "No major risks detected", "No se detectaron riesgos principales")}</span>}</div><h3>{tx(lang, "Recommended Focus", "Enfoque recomendado")}</h3><p>{analysis.focus}</p><small>{tx(lang, "Close probability estimate: ", "Estimación de probabilidad de cierre: ")}{analysis.probability}% · {analysis.provider === "local" ? tx(lang, "Local engine", "Motor local") : "OpenAI"}</small><button className="primary" disabled={busy} onClick={refresh}><RefreshCw size={15} />{busy ? tx(lang, "Generating...", "Generando...") : tx(lang, "Refresh Analysis", "Actualizar análisis")}</button></section>;
}
