import type { Language, Lead } from "../../types";

export type SalesAction = { prospectId:string; priority:"low"|"medium"|"high"; actionType:"whatsapp"|"email"|"follow_up"|"call"; title:string; reason:string; recommendation:string; potentialValue:number };
const days=(value?:string)=>value?Math.floor((Date.now()-new Date(value).getTime())/86400000):0;
const tx=(lang:Language,en:string,es:string)=>lang==="es"?es:en;
export const nextBestAction=(lead:Lead,lang:Language="en"):SalesAction|undefined=>{
  const name=`${lead.firstName} ${lead.lastName}`.trim();
  if(lead.stage==="won")return {prospectId:lead.id,priority:"low",actionType:"follow_up",title:tx(lang,"Start post-sale onboarding", "Iniciar onboarding postventa"),reason:tx(lang,"This opportunity has been closed as Won.","Esta oportunidad se cerró como Ganada."),recommendation:tx(lang,"Confirm payment, onboarding, production, or delivery requirements.","Confirmar pago, onboarding, producción o requisitos de entrega."),potentialValue:lead.potentialValue};
  if(lead.stage==="lost")return {prospectId:lead.id,priority:"low",actionType:"follow_up",title:tx(lang,"Document the loss", "Documentar la pérdida"),reason:tx(lang,"This opportunity is closed as Lost.","Esta oportunidad se cerró como Perdida."),recommendation:tx(lang,"Record the reason and consider a future reactivation strategy.","Registrar el motivo y considerar una estrategia de reactivación futura."),potentialValue:lead.potentialValue};
  if(lead.quoteStatus==="accepted")return {prospectId:lead.id,priority:"high",actionType:"call",title:tx(lang,`Confirm the next step with ${name}`,`Confirmar el siguiente paso con ${name}`),reason:tx(lang,"The customer accepted the quote.","El cliente aceptó la cotización."),recommendation:tx(lang,"Confirm payment, deposit, contract, or project start. Do not ask for approval again.","Confirmar pago, depósito, contrato o inicio del proyecto. No pedir aprobación nuevamente."),potentialValue:lead.potentialValue};
  const inactivity=days(lead.lastContact||lead.updatedAt||lead.createdAt); const actionType=lead.phone||lead.whatsapp?"whatsapp":lead.email?"email":"follow_up"; const priority=(lead.potentialValue>=1000||["interested","appointment","quote_sent"].includes(lead.stage))?"high":lead.stage==="new"?"medium":"low";
  const byStage:Record<string,[string,string,string,string]>={new:["Make the first contact","Realizar el primer contacto","Introduce yourself and invite a simple reply.","Preséntate e invita una respuesta sencilla."],contacted:["Plan the next contact","Planificar el siguiente contacto","Wait for a response or schedule a thoughtful second touch.","Esperar respuesta o programar un segundo contacto oportuno."],replied:["Discover the need","Descubrir la necesidad","Ask focused questions and share relevant information.","Hacer preguntas concretas y compartir información relevante."],information_sent:["Confirm receipt","Confirmar recepción","Make sure the information was received and schedule follow-up.","Confirmar que recibió la información y programar seguimiento."],interested:["Move toward a meeting or proposal","Avanzar hacia cita o cotización","Qualify the need and prepare the next commercial step.","Calificar la necesidad y preparar el siguiente paso comercial."],appointment:["Prepare the appointment","Preparar la cita","Confirm the meeting and document the prospect's needs.","Confirmar la cita y documentar las necesidades del prospecto."],quote_sent:["Follow up on the quote","Dar seguimiento a la cotización","Confirm receipt, answer questions, and plan the closing conversation.","Confirmar recepción, resolver dudas y planificar la conversación de cierre."]};
  const item=byStage[lead.stage]||byStage.contacted; return {prospectId:lead.id,priority,actionType,title:tx(lang,item[0],item[1]),reason:inactivity>=3?tx(lang,`No activity for ${inactivity} days`,`Sin actividad durante ${inactivity} días`):tx(lang,"Based on the current opportunity stage.","Basado en la etapa actual de la oportunidad."),recommendation:tx(lang,item[2],item[3]),potentialValue:lead.potentialValue};
};
export const salesActions=(leads:Lead[],lang:Language="en")=>leads.map(lead=>nextBestAction(lead,lang)).filter((x):x is SalesAction=>!!x).sort((a,b)=>({high:3,medium:2,low:1}[b.priority]-{high:3,medium:2,low:1}[a.priority])||b.potentialValue-a.potentialValue);
